### ISSUE TITLE
Support for multiple Host in the Engine

### ISSUE THREAD

**Issue by HerveMARTIN** [antoineco/aco-tomcat#101]
Inside server.xml we need to add another Host entry for a second webapp.
To be backward compatible, I suggest using a hash parameter named other_hosts or additionnal_hosts.
I'll do a PR soon.

**Comment by HerveMARTIN** [comment]
Hum we will need to deal with nested components (Logger and Context for example), not simple...

**Comment by HerveMARTIN** [comment]
I would suggest to use a nested hash, like the one after, but it will not be backward compatible...
```
host: 
  - name: www.example.org
    appBase: webapps
    logger:
      - className: org.apache.catalina.logger.FileLogger
        directory: app/logs
    context:
      - docBase: /home/app
        crossContext: true
  - name: cas.example.org
    appBase: webapps
    logger:
      - className: org.apache.catalina.logger.FileLogger
        directory: cas/logs
    context:
      - docBase: /home/cas
        crossContext: true
```
