### ISSUE TITLE
JMX auth files support

### ISSUE THREAD

**Issue by HerveMARTIN** [antoineco/aco-tomcat#98]
To enable JMX with authentication, we need to add java_opts or catalina_opts and fill two files : the access and the password file.
Would it be ok for you if I do a PR to support the creation of theses files?
We would need one more parameter : 
$jmx_users which should contain a hash of this type : 
```
- myReadOnlyUser: 
  role: readonly
  password: changeme
- myReadWriteUser:
  role: readwrite
  password: changemetoo
...
```
